name: Backend Deployment

on:
  push:
    branches:
      - master
env:
  WEBAPP_NAME: enggeinus
  PUBLISHED_PACKAGE_PATH: EngGenius.Api/publish
  CONFIGURATION: Release
  DOTNET_VERSION: 8.0.x
  WORKING_DIRECTORY: EngGenius.Api
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore ${{ env.WORKING_DIRECTORY }}

    - name: Build
      run: dotnet build ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Test
      run: dotnet test ${{ env.WORKING_DIRECTORY }} --no-build

    - name: Publish
      run: dotnet publish ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-build --output ${{ env.PUBLISHED_PACKAGE_PATH }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: ${{ env.PUBLISHED_PACKAGE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: webapp
          path: ${{ env.PUBLISHED_PACKAGE_PATH }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9E2BA28105F84AFD89401E2726EF1DBD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_402FD9B787BC4B3288DE743B007B8FE8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B859B03F7EC74D26A2343B44FAEAF1F4 }}

      - name: Deploy to Azure
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: 'Production'
          package: ${{ env.PUBLISHED_PACKAGE_PATH }}
          
